### ISSUE TITLE
[Bug] docker-compose.yml 中设置 环境变量 没用

### ISSUE THREAD

**Issue by Liner03** [Cp0204/quark-auto-save#42]
### What happened

这是我修改的
```yml
environment:
  WEBUI_USERNAME: "root"
  WEBUI_PASSWORD: "6666123"
```
而实际的 `username` 和 `password` 仍为默认密码 `admin` `admin123`
需手动修改配置 `quark_auto_save/quark-auto-save/config/quark_config.json`

#### Config
```json
{}
```
#### Log
```
text
```

### Operating environment

Docker

### Environment version

v27.3.1
